In [6]:
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

import pandas as pd

In [11]:
file = open('../config/mongo', 'r')
mongo = file.read().splitlines()
file.close()
uri = f"mongodb+srv://{mongo[0]}:{mongo[1]}@discordcluster.ujcowjs.mongodb.net/?retryWrites=true&w=majority"
mongo_client = MongoClient(uri, server_api=ServerApi('1'))
db = mongo_client.my_database
db = db.posts

In [14]:
df = pd.DataFrame(list(db.find()))

In [15]:
df

,_id,content,id,author.global_name,author.name,mention_everyone,pinned,reactions,channel.name,mentions,role_mentions,guild.id,guild.name
0,65aec59ab34d51f31e7205e4,test,1199077135063732365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,65aec5a0b34d51f31e7205e5,$hello,1199077159969509407,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,65aec5a1b34d51f31e7205e6,Hello!,1199077161085181995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,65aec961486a2b37a86a6859,$hello,1199081188468469860,Lion,lion4567714,False,False,[],NaN,NaN,NaN,NaN,NaN
4,65aec961486a2b37a86a685a,Hello!,1199081189739335680,None,Lion Bot,False,False,[],NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
437,65aefdb3595078a7c51bc7c2,/test test,1199158338118754426,Lion,lion4567714,False,False,[],general,NaN,[],9.762517e+17,Bot Harem
438,65aefdb4595078a7c51bc7c3,/test,1199158343340658742,Lion,lion4567714,False,False,[],general,NaN,[],9.762517e+17,Bot Harem
439,65aefe3d595078a7c51bc7c4,$test,1199158918069370900,Lion,lion4567714,False,False,[],general,NaN,[],9.762517e+17,Bot Harem
440,65aefe46595078a7c51bc7c5,$ping,1199158956665339945,Lion,lion4567714,False,False,[],general,NaN,[],9.762517e+17,Bot Harem
441,65aefe5ed4700a4a5aeef3b4,/test,1199159053578948690,Lion,lion4567714,False,False,[],general,NaN,[],9.762517e+17,Bot Harem